namespace Mup.Elements
{
    /// <summary>Represents the base class for all parse tree node types.</summary>
    public abstract class Element
    {
        /// <summary>Accepts a <paramref name="visitor"/> which can be used to generate output from the parse tree.</summary>
        /// <param name="visitor">The visitor used to traverse the parse tree.</param>
        /// <exception cref="System.NullReferenceException">Thrown when <paramref name="visitor"/> is <c>null</c>.</exception>
        public abstract void Accept(ParseTreeVisitor visitor);

        /// <summary>Accepts a <paramref name="visitor"/> which can be used to generate output from the parse tree.</summary>
        /// <typeparam name="TResult">The result type that the <paramref name="visitor"/> generates.</typeparam>
        /// <param name="visitor">The visitor used to traverse the parse tree.</param>
        /// <returns>Returns the result generated by the <paramref name="visitor"/>.</returns>
        /// <exception cref="System.NullReferenceException">Thrown when <paramref name="visitor"/> is <c>null</c>.</exception>
        public TResult Accept<TResult>(ParseTreeVisitor<TResult> visitor)
        {
            Accept((ParseTreeVisitor)visitor);
            return visitor.GetResult();
        }
    }
}