using System;
using System.Threading;
using System.Threading.Tasks;

namespace Mup
{
    /// <summary>A helper class containing extension methods for parse tasks.</summary>
    public static class ParseTreeExtensions
    {
        /// <summary>Visits the <see cref="IParseTree"/> after the parse task completes.</summary>
        /// <param name="parseTask">The task generated from calling any of the ParseAsync methods on an <see cref="IMarkupParser"/>.</param>
        /// <param name="visitor">The visitor to use for traversing the resulting parse tree.</param>
        /// <returns>Returns a <see cref="Task"/> representing the asynchronous operation.</returns>
        /// <exception cref="ArgumentNullException">Thrown when either <paramref name="parseTask"/> or <paramref name="visitor"/> are null.</exception>
        public static Task With(this Task<IParseTree> parseTask, ParseTreeVisitor visitor)
            => parseTask.With(visitor, CancellationToken.None);

        /// <summary>Visits the <see cref="IParseTree"/> after the parse task completes.</summary>
        /// <param name="parseTask">The task generated from calling any of the ParseAsync methods on an <see cref="IMarkupParser"/>.</param>
        /// <param name="visitor">The visitor to use for traversing the resulting parse tree.</param>
        /// <param name="cancellationToken">A token that can be used to signal a cancellation request.</param>
        /// <returns>Returns a <see cref="Task"/> representing the asynchronous operation.</returns>
        /// <exception cref="ArgumentNullException">Thrown when either <paramref name="parseTask"/> or <paramref name="visitor"/> are null.</exception>
        public static async Task With(this Task<IParseTree> parseTask, ParseTreeVisitor visitor, CancellationToken cancellationToken)
        {
            if (parseTask == null)
                throw new ArgumentNullException(nameof(parseTask));
            if (visitor == null)
                throw new ArgumentNullException(nameof(visitor));

            var parseTree = await parseTask.ConfigureAwait(false);
            await parseTree.AcceptAsync(visitor, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>Visits the <see cref="IParseTree"/> after the parse task completes.</summary>
        /// <typeparam name="TResult">The type which is constructed after visitng a parse tree.</typeparam>
        /// <param name="parseTask">The task generated from calling any of the ParseAsync methods on an <see cref="IMarkupParser"/>.</param>
        /// <param name="visitor">The visitor to use when transforming the parse tree.</param>
        /// <returns>Returns the result generated by the <paramref name="visitor"/> wrapped in a <see cref="Task{TResult}"/>.</returns>
        /// <exception cref="ArgumentNullException">Thrown when either <paramref name="parseTask"/> or <paramref name="visitor"/> are null.</exception>
        public static Task<TResult> With<TResult>(this Task<IParseTree> parseTask, ParseTreeVisitor<TResult> visitor)
            => parseTask.With(visitor, CancellationToken.None);

        /// <summary>Visits the <see cref="IParseTree"/> after the parse task completes.</summary>
        /// <typeparam name="TResult">The type which is constructed after visitng a parse tree.</typeparam>
        /// <param name="parseTask">The task generated from calling any of the ParseAsync methods on an <see cref="IMarkupParser"/>.</param>
        /// <param name="visitor">The visitor to use when transforming the parse tree.</param>
        /// <param name="cancellationToken">A token that can be used to signal a cancellation request.</param>
        /// <returns>Returns the result generated by the <paramref name="visitor"/> wrapped in a <see cref="Task{TResult}"/>.</returns>
        /// <exception cref="ArgumentNullException">Thrown when either <paramref name="parseTask"/> or <paramref name="visitor"/> are null.</exception>
        public static async Task<TResult> With<TResult>(this Task<IParseTree> parseTask, ParseTreeVisitor<TResult> visitor, CancellationToken cancellationToken)
        {
            if (parseTask == null)
                throw new ArgumentNullException(nameof(parseTask));
            if (visitor == null)
                throw new ArgumentNullException(nameof(visitor));

            var parseTree = await parseTask.ConfigureAwait(false);
            var result = await parseTree.AcceptAsync(visitor, cancellationToken).ConfigureAwait(false);
            return result;
        }
    }
}